2017-04-26 20:54:05,337 - default_file_logger - ERROR - Thread-8 -  Could not prse json, returning None
2017-04-26 20:54:06,674 - default_file_logger - ERROR - Thread-10 -  Could not prse json, returning None
2017-04-26 20:54:43,102 - default_file_logger - ERROR - Thread-34 -  Could not prse json, returning None
2017-04-26 21:10:02,361 - default_file_logger - ERROR - Thread-67 -  Could not prse json, returning None
2017-04-26 21:10:09,848 - default_file_logger - ERROR - Thread-77 -  Could not prse json, returning None
2017-04-26 21:23:36,478 - default_file_logger - ERROR - Thread-106 -  Could not prse json, returning None
2017-04-30 20:53:20,465 - default_file_logger - ERROR - Thread-22 -  Could not prse json, returning None
2017-05-01 22:56:34,051 - default_file_logger - ERROR - Thread-37 -  GET loop Timeout
2017-05-01 22:56:34,130 - default_file_logger - ERROR - Thread-37 -  The request for results at 3280 from https://www.google.com/finance?output=json&noIL=1&start=3280&num=20&restype=company&q=[currency%20%3D%3D%20%22USD%22%20%26%20%28exchange%20%3D%3D%20%22NASDAQ%22%29%20%26%20%28market_cap%20%3E%3D%200%29%20%26%20%28market_cap%20%3C%3D%20746660000000%29] failed.
2017-05-01 22:58:42,646 - default_file_logger - ERROR - Thread-7 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000017562F474A8>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 22:59:10,684 - default_file_logger - ERROR - Thread-28 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000017564596D68>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 22:59:33,799 - default_file_logger - ERROR - Thread-42 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000017562F17F28>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 22:59:55,428 - default_file_logger - ERROR - Thread-59 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000175645E4438>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 23:00:16,253 - default_file_logger - ERROR - Thread-70 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001756462E588>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 23:00:58,750 - default_file_logger - ERROR - Thread-96 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000175646C0978>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 23:02:23,876 - default_file_logger - ERROR - Thread-142 -  Could not prse json, returning None
2017-05-01 23:03:12,814 - default_file_logger - ERROR - Thread-165 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000017564866278>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-01 23:03:17,323 - default_file_logger - ERROR - Thread-170 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000175648732B0>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:21:54,970 - default_file_logger - ERROR - Thread-15 -  Could not prse json, returning None
2017-05-03 21:23:04,613 - default_file_logger - ERROR - Thread-57 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001B5C61377F0>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:24:37,479 - default_file_logger - ERROR - Thread-125 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001B5C77B8B38>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:25:48,911 - default_file_logger - ERROR - Thread-174 -  Could not prse json, returning None
2017-05-03 21:29:54,540 - default_file_logger - ERROR - Thread-362 -  Could not prse json, returning None
2017-05-03 21:34:27,019 - default_file_logger - ERROR - Thread-597 -  Could not prse json, returning None
2017-05-03 21:34:35,290 - default_file_logger - ERROR - Thread-601 -  Could not prse json, returning None
2017-05-03 21:34:52,408 - default_file_logger - ERROR - Thread-617 -  Could not prse json, returning None
2017-05-03 21:35:23,267 - default_file_logger - ERROR - Thread-643 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001B5C7879E48>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:36:03,748 - default_file_logger - ERROR - Thread-676 -  Could not prse json, returning None
2017-05-03 21:38:03,333 - default_file_logger - ERROR - Thread-763 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001B5C67280F0>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:43:18,431 - default_file_logger - ERROR - Thread-27 -  Could not prse json, returning None
2017-05-03 21:43:20,016 - default_file_logger - ERROR - Thread-33 -  Could not prse json, returning None
2017-05-03 21:45:12,593 - default_file_logger - ERROR - Thread-133 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021B622BF1D0>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:46:18,476 - default_file_logger - ERROR - Thread-188 -  Could not prse json, returning None
2017-05-03 21:47:30,044 - default_file_logger - ERROR - Thread-253 -  Could not prse json, returning None
2017-05-03 21:48:12,114 - default_file_logger - ERROR - Thread-287 -  Could not prse json, returning None
2017-05-03 21:48:37,572 - default_file_logger - ERROR - Thread-306 -  IP api call failed; SOCKSHTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ConnectTimeoutError(<requests.packages.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021B639B4908>, 'Connection to api.ipify.org timed out. (connect timeout=5)'))
2017-05-03 21:48:45,038 - default_file_logger - ERROR - Thread-309 -  Could not prse json, returning None
